strings = {
	"This is deliberate. The meter is not supposed to go this far up, but the data received can.",
	"OK, you can stop it now. Turn around.",
	"The display is stuck. It's not funny anymore.",
	"I hate you.",
	"Fine. Let's play a game.",
	"Ha, you had to go back to read these!",
	"They're full of nothing, but they're still funny.",
	"Maybe I should have thrown the Navy Seal copypasta in here.",
	"What?",
	"Why did I write all this stuff?",
	"I don't really know.",
	"It's good Lua practice though, so there's that.",
	"So thanks for that.",
	"Yeah, bet you feel real silly right now.",
	"There's nothing else left.",
	"Really, you can check the code.",
	toprint = false,
	numtoprint = 0,
}

